name: Publish Header

on:
  push:
    tags: v*

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: bundle header
      run: |
        mkdir amf-headers-${{ github.ref_name }}
        mv amf/public/include amf-headers-${{ github.ref_name }}/AMF
        tar czf AMF-headers-${{ github.ref_name }}.tar.gz amf-headers-${{ github.ref_name }}/
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: AMF-headers-${{ github.ref_name }}.tar.gz
